#!/usr/bin/env bash

set -e

only_repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
shard_name=${only_repo%.cr}
snek_name=$(echo $shard_name | sed 's/-/_/g')
constant_name=$(echo $shard_name | sed -r 's/(^|_|-)([a-z])/\U\2/g')

echo "Merging template with crystal init lib"
crystal init lib $snek_name
cp $snek_name/README.md .
cp -rn $snek_name/* .
cp -rn $snek_name/.?* .
rm -rf $snek_name/

echo "Adding default dependencies to shard.yml"
cat <<EOF >> shard.yml
dependencies:
  habitat:
    github: luckyframework/habitat

development_dependencies:
  ameba:
    github: crystal-ameba/ameba
    version: ~> 0.14
  spectator:
    github: icy-arctic-fox/spectator
    version: ~> 0.10
EOF

echo "Installing spectator to specs"
echo 'require "spectator"' >> spec/spec_helper.cr
cat <<EOF > spec/${snek_name}_spec.cr
require "./spec_helper"

Spectator.describe ${constant_name} do
  it "should have a version" do
    expect(${constant_name}::VERSION).to be_a(String)
  end
end
EOF

echo "Removing install specific files"
rm -f .github/workflows/init.yml
rm -f .github/workflows/init
